# Generated by Django 5.0 on 2024-01-02 06:30

import core.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('Nilaiid', models.BigAutoField(primary_key=True, serialize=False)),
                ('NamaNilai', models.CharField(max_length=50)),
                ('RangeNilai', models.CharField(max_length=250)),
                ('Warna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanAkreditasi',
            fields=[
                ('Akreditasiid', models.BigAutoField(primary_key=True, serialize=False)),
                ('GambarKomponenMutuLulusan', models.ImageField(blank=True, null=True, upload_to=core.models.KomponenMutuLulusan)),
                ('KomponenMutuLulusan', models.ImageField(upload_to='')),
                ('GambarKomponenProsesPembelajaran', models.ImageField(blank=True, null=True, upload_to=core.models.KomponenProsesPembelajaran)),
                ('KomponenProsesPembelajaran', models.ImageField(upload_to='')),
                ('GambarKomponenMutuGuru', models.ImageField(blank=True, null=True, upload_to=core.models.KomponenMutuGuru)),
                ('KomponenMutuGuru', models.ImageField(upload_to='')),
                ('GambarKomponenManajemenSekolah', models.ImageField(blank=True, null=True, upload_to=core.models.KomponenManajemenSekolah)),
                ('KomponenManajemenSekolah', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanSekolah',
            fields=[
                ('PengajuanId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Gambar', models.ImageField(blank=True, null=True, upload_to=core.models.GambarSekolah)),
                ('TanggalAjukan', models.DateField(auto_now_add=True, null=True)),
                ('NamaSekolah', models.CharField(max_length=250)),
                ('NamaKepalaSekolah', models.CharField(max_length=250)),
                ('NamaPengawasSekolah', models.CharField(max_length=250)),
                ('AlamatSekolah', models.CharField(max_length=500)),
                ('JumlahGuru', models.IntegerField(blank=True, null=True)),
                ('JumlahRuangKelas', models.IntegerField(blank=True, null=True)),
                ('JumlahPegawai', models.IntegerField(blank=True, null=True)),
                ('StatusAkreditasi', models.CharField(choices=[('A', 'SANGAT BAIK'), ('B', 'BAIK'), ('C', 'CUKUP'), ('TT', 'TIDAK TERAKREDITASI')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PolygonModel',
            fields=[
                ('PolygonId', models.BigAutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('PengajuanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pengajuansekolah')),
            ],
        ),
    ]
