# Generated by Django 5.0 on 2024-01-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nilai_pengajuanakreditasi_pengajuansekolah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='TataTertib',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
