# Generated by Django 5.0 on 2024-01-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pengajuanakreditasi_tatatertib'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='AnalisisPencapaianKompetensi',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='BuktiDaftarHadir',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='BuktiKegiatanDenganPihakLuar',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='BuktiKegiatanEkstrakulikuler',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='BuktiKegiatanOsis',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='DaftarPenggunaanSapras',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='DataNilaiUjian',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarAnalisisPencapaianKompetensi',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarBuktiDaftarHadir',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarBuktiKegiatanDenganPihakLuar',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarBuktiKegiatanEkstrakulikuler',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarBuktiKegiatanOsis',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarDaftarPenggunaanSapras',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarDataNilaiUjian',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarJadwalRemedial',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarKisiKisiSoalInstrumenHasilPenilaian',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanDariGuru',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanDariSiswa',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanEvaluasi',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanHasilKaryaPrestasi',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanHasilTracerStudy',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanJadwalKegiatan',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanKegiatanDiseminasi',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanKegiatanProgramKreatif',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanPengembanganGuru',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLaporanPrestasiSiswaLomba',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarLembarKerjaSiswa',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarPortofolioTugasMateriPengembangan',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarPortofolioTugasSiswa',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarRKAS1Tahun',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarRKS4Tahun',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarRPP',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarSertifikat',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambarTataTertib',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='GambartataTertib',
            field=models.ImageField(blank=True, null=True, upload_to=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], max_length=50)),
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='JadwalRemedial',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='KisiKisiSoalInstrumenHasilPenilaian',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanDariGuru',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanDariSiswa',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanEvaluasi',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanHasilKaryaPrestasi',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanHasilTracerStudy',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanJadwalKegiatan',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanKegiatanDiseminasi',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanKegiatanProgramKreatif',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanPengembanganGuru',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LaporanPrestasiSiswaLomba',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='LembarKerjaSiswa',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='PengajuanId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.pengajuansekolah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='PortofolioTugasMateriPengembangan',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='PortofolioTugasSiswa',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='RKAS1Tahun',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='RKS4Tahun',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='RPP',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuanakreditasi',
            name='Sertifikat',
            field=models.CharField(choices=[('ADA', 'ADA'), ('tIDAK ADA', 'TIDAK ADA')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengajuansekolah',
            name='JumlahSiswa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuansekolah',
            name='Tahun',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengajuanakreditasi',
            name='KomponenManajemenSekolah',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pengajuanakreditasi',
            name='KomponenMutuGuru',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pengajuanakreditasi',
            name='KomponenMutuLulusan',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pengajuanakreditasi',
            name='KomponenProsesPembelajaran',
            field=models.IntegerField(max_length=100),
        ),
    ]
