# Generated by Django 5.0 on 2024-01-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pengajuanakreditasi_buktisaksiataupenghargaan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengajuansekolah',
            old_name='Tahun',
            new_name='TahunBerdiri',
        ),
    ]
