# Generated by Django 5.0 on 2024-01-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_tahun_pengajuansekolah_tahunberdiri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengajuanakreditasi',
            old_name='Akreditasiid',
            new_name='AkreditasiId',
        ),
        migrations.RenameField(
            model_name='pengajuanakreditasi',
            old_name='PengajuanId',
            new_name='SekolahId',
        ),
        migrations.RenameField(
            model_name='pengajuansekolah',
            old_name='PengajuanId',
            new_name='SekolahId',
        ),
        migrations.RenameField(
            model_name='polygonmodel',
            old_name='PengajuanId',
            new_name='SekolahId',
        ),
    ]
